### ISSUE TITLE
Question: WOFF2  ?

### ISSUE THREAD

**Issue by idefy** [nfroidure/gulp-ttf2woff#2]
Is Woff2 support planned to be added soon to this great plugin ?

**Comment by nfroidure** [comment]
Actuallt the new gulp-iconfont version supports woff2 but with an external binary you'll have to compile yourself on your platform. It will remain the same until a node module appears. see https://github.com/google/woff2/issues/20

**Comment by nfroidure** [comment]
Finally made a module, have to incorporate it to avoid the need to install and compile my woff2 fork https://github.com/nfroidure/ttf2woff2
