### ISSUE TITLE
could you update gulp?

### ISSUE THREAD

**Issue by caohenghu** [nfroidure/gulp-ttf2woff#6]
when I install, it tell me:
warning gulp-ttf2woff > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by Jelle-S** [comment]
@ninbryan @ninbryan Pretty please? :)

**Comment by nfroidure** [comment]
Hi! Would merge any PR doing so but since I'm not using it since a while, I won't have time allocated for this.

**Comment by nfroidure** [comment]
Also, would give collaborator access to both the repo / npm module if you wish to help maintain it.

**Comment by Jelle-S** [comment]
@nfroidure 
@hangy created that PR: #7  :)
